NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-23054-ca-org17.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-23054-ca-org17.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-23054-ca-org17.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-23054-ca-org17.pem
    OrganizationalUnitIdentifier: orderer
