name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  # channelName of mychannel matches the name of the channel created by test network
  - channelName: mychannel
    # the chaincodeIDs of all the fabric chaincodes in caliper-benchmarks
    contracts:
    - id: datatrading

organizations:
  - mspid: Org1MSP
    # Identities come from cryptogen created material for test-network
    identities:
      certificates:
      - name: 'Admin@org1.example.com'
        clientPrivateKey:
          path: '../deTrade-chain/deTrade-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/31053314099125ca611ec1e7922c5d52f7072cc56469a45dd5018377278e10df_sk'
        clientSignedCert:
          path: '../deTrade-chain/deTrade-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../deTrade-chain/deTrade-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml'
      discover: true

