NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-24054-ca-org18.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-24054-ca-org18.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-24054-ca-org18.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-24054-ca-org18.pem
    OrganizationalUnitIdentifier: orderer
