NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-26054-ca-org20.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-26054-ca-org20.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-26054-ca-org20.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-26054-ca-org20.pem
    OrganizationalUnitIdentifier: orderer
