# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.7'
networks:
  test:
    name: fabric_test
services:
  ca_org1:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    container_name: ca_${ORG1}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-${ORG1}
      - FABRIC_CA_SERVER_PORT=${CAPORT1}
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:${CAOPLISSEN1}
    ports:
      - "${CAPORT1}:${CAPORT1}"
      - "${CAOPLISSEN1}:${CAOPLISSEN1}"
    volumes:
      - ../organizations/fabric-ca/${ORG1}:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - test
  ca_org2:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    container_name: ca_${ORG2}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-${ORG2}
      - FABRIC_CA_SERVER_PORT=${CAPORT2}
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:${CAOPLISSEN2}
    ports:
      - "${CAPORT2}:${CAPORT2}"
      - "${CAOPLISSEN2}:${CAOPLISSEN2}"
    volumes:
      - ../organizations/fabric-ca/${ORG2}:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - test
  ca_org3:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    container_name: ca_${ORG3}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-${ORG3}
      - FABRIC_CA_SERVER_PORT=${CAPORT3}
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:${CAOPLISSEN3}
    ports:
      - "${CAPORT3}:${CAPORT3}"
      - "${CAOPLISSEN3}:${CAOPLISSEN3}"
    volumes:
      - ../organizations/fabric-ca/${ORG3}:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - test
  ca_org4:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    container_name: ca_${ORG4}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-${ORG4}
      - FABRIC_CA_SERVER_PORT=${CAPORT4}
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:${CAOPLISSEN4}
    ports:
      - "${CAPORT4}:${CAPORT4}"
      - "${CAOPLISSEN4}:${CAOPLISSEN4}"
    volumes:
      - ../organizations/fabric-ca/${ORG4}:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - test
  ca_org5:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    container_name: ca_${ORG5}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-${ORG5}
      - FABRIC_CA_SERVER_PORT=${CAPORT5}
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:${CAOPLISSEN5}
    ports:
      - "${CAPORT5}:${CAPORT5}"
      - "${CAOPLISSEN5}:${CAOPLISSEN5}"
    volumes:
      - ../organizations/fabric-ca/${ORG5}:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - test
  ca_orderer:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    container_name: ca_${ORDERER}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-${ORDERER}
      - FABRIC_CA_SERVER_PORT=${CAPORTORD}
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:${CAOPLISSENORD}
    ports:
      - "${CAPORTORD}:${CAPORTORD}"
      - "${CAOPLISSENORD}:${CAOPLISSENORD}"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    networks:
      - test
