version: '3.7'

volumes:
  peer0.org15.example.com:

networks:
  test:
    name: fabric_test

services:
  peer0.org15.example.com:
    container_name: peer0.org15.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/docker/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org15.example.com
      - CORE_PEER_ADDRESS=peer0.org15.example.com:21051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:21051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org15.example.com:21052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:21052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org15.example.com:21051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org15.example.com:21051
      - CORE_PEER_LOCALMSPID=Org15MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org15.example.com:21446
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org15"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s

    volumes:
      - ../organizations/peerOrganizations/org15.example.com/peers/peer0.org15.example.com:/etc/hyperledger/fabric
      - peer0.org15.example.com:/var/hyperledger/production
      - ../compose/docker:/etc/docker

    working_dir: /root
    command: peer node start
    ports:
      - 21051:21051
      - 21446:21446
    networks:
      - test
