NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-22054-ca-org16.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-22054-ca-org16.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-22054-ca-org16.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-22054-ca-org16.pem
    OrganizationalUnitIdentifier: orderer
