NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-25054-ca-org19.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-25054-ca-org19.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-25054-ca-org19.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-25054-ca-org19.pem
    OrganizationalUnitIdentifier: orderer
